### ISSUE TITLE
Produce a release?

### ISSUE THREAD

**Issue by rouson** [OpenFortranProject/open-fortran-parser#107]
With the likelihood that OpenCoarrays will add the OFP parser as a dependency, it would be great to produce a tagged release tar ball via GitHub's release feature.  That would give external teams a static snapshot of OFP that we can target and know that we're always getting the same thing until we decide proactively to update to a new release.  

FYI, in case you'd like to track download statistics, I also recommend creating your own tar ball via "git archive" and posting it.  There is an [external site](http://www.somsubhra.com/github-release-stats/) that can be used to track downloads of any files you proactively post.  Unfortunately, there does not appear to be a mechanism for tracking downloads of the compressed archives that GitHub will generate automatically for each release.

I'll be glad to help with any of the above if so desired.

**Comment by zbeekman** [comment]
I agree with Damian, but will also note that git submodules can freeze at a given commit

**Comment by mjsottile** [comment]
I just noticed this - this is another case where @rasmussn is likely not paying attention to the github issues.  Best to ping him on e-mail to get him to pay attention here.

**Comment by rouson** [comment]
@mjsottile Thanks for the reply.  I emailed Craig.

**Comment by rouson** [comment]
Come to think of it, I'll close this comment.  Subsequent to my original post, @rasmussn explained to me that this repository is a legacy repository.  We're now incorporating [ofp-sdf](https://github.com/OpenFortranProject/ofp-sdf) into OpenCoarrays instead.  I'd really like to contribute some text for the ofp-sdf README file that provides more information, including making it clear that it's the vision of OFP that remains under active development while the older [ofp](https://github.com/OpenFortranProject/open-fortran-parser) repository is preferred for new projects.

**Comment by zbeekman** [comment]
It might be wise to point people to ofp-sdf from this repo's README.md too.

**Comment by rasmussn** [comment]
I can't find where my old rasmussn email account is being used on github.

-craig

**Comment by rouson** [comment]
@rasmussn  Assuming Open Fortran Project is set up as a GitHub organization, I assume you're able to log in either as the organization or as yourself.  When you log in as yourself, click the icon in the upper right corner of the page. Select "Settings" from the drop-down menu.  On the left bar, select email.

**Comment by rasmussn** [comment]
I had done this very thing and got confused because of old age (good excuse
for about everything I've found).

The confusion was that my old LANL email was rasmussn so Matt and I saw
@rasmussn and thought it was my old rasmussn@lanl.gov account.

Thanks,

-craig
